Hw13 calendar
ekhvalov/golang-otus pull request #17
Opened 2022-10-07 08:14 UTC by ekhvalov

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [x] Makefile заполнен и пайплайн зеленый - 1 балл
- [x] Реализовано GRPC API и `make generate` - 3 балла
- [x] Реализовано HTTP API - 2 балла
- [x] Написаны юнит-тесты на API - до 2 баллов
- [x] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-10-30 11:31 UTC, Nikscorp requested changes
Владимир, добрый день!

Отличная работа, функционал реализован в соответствие с требованиями. Мне понравилась аккуратность и лаконичность вашего решения.

На данный момент отправляю PR на доработку, так как я не увидел sql реализации хранилища, которая должна была быть реализована еще в предыдущем ДЗ. Если она не попала в бранч — добавьте, пожалуйста.

Также рекомендуется исправить / подумать / отписаться по остальным замечаниям в PR.

2022-10-30 11:31 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	_ context.Context,
контекст плохо игнорировать — его нужно принимать и передавать во все нижележащие функции, работающие с io. При его отмене мы сможем отменить дорогостояющую операцию в БД, например

2022-10-30 11:31 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +type Server interface {
актуально для всех пакетов: в go интерфейсы чаще объявляют на стороне, которая их использует, а не на той, которая объявляет структуры: https://github.com/golang/go/wiki/CodeReviewComments#interfaces

2022-10-30 11:31 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/app/event/command/create_event.go
> +type CreateEventRequestHandler interface {
не очень понял зачем скрывать все методы event-a за интерфейсами в app.go. Тут достаточно просто объявить методы структуры. Также мне кажется разделение на command и query излишне

2022-10-30 11:31 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +func isOverlapped(e1, e2 event.Event) bool {
а такой функционал есть в ТЗ? Если хотите реализовать такое, то как минимум нужно разбиение по пользователям и какой-нибудь индекс по времени.

Я бы убрал этот функционал, чтобы не усложнять логику

2022-11-02 03:16 UTC, ekhvalov commented on hw12_13_14_15_calendar/api/grpc/EventService.proto
> +  rpc CreateEvent(CreateEventRequest) returns (CreateEventReply) {}
Исправил

2022-11-02 03:16 UTC, ekhvalov commented on hw12_13_14_15_calendar/api/grpc/EventService.proto
> +  string title = 2;
Исправил

2022-11-02 03:16 UTC, ekhvalov commented on hw12_13_14_15_calendar/api/grpc/EventService.proto
> +message CreateEventReply {
Исправил

2022-11-02 03:18 UTC, ekhvalov commented on hw12_13_14_15_calendar/api/grpc/EventService.proto
> +message Event {
Не понял как именно это сделать кроме как `Event event = 1'`, но это добавляет лишний уровень вложенности.
Как-то иначе можно сделать?

2022-11-02 03:18 UTC, ekhvalov commented on hw12_13_14_15_calendar/cmd/calendar/calendar.go
> +	grpcServer, err := internalgrpc.NewServer(calendar, logg)
Исправил

2022-11-02 03:27 UTC, ekhvalov commented on hw12_13_14_15_calendar/cmd/calendar/calendar.go
> +		if err := httpServer.Start(srvAddr); err != nil {
Исправил

2022-11-02 03:31 UTC, ekhvalov commented on hw12_13_14_15_calendar/cmd/calendar/calendar.go
> +	}(&wg)
Исправил

2022-11-02 03:31 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/storage/memory/id_generator.go
> +package memorystorage
Да, реализации не было, добавил.

2022-11-02 03:36 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +		UserID:       "10",
Исправил

2022-11-02 06:09 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	_ context.Context,
Добавил контекст.

2022-11-02 06:14 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +type Server interface {
Тут я просто хотел скрыть от вызывающего кода другие методы (GRPC реализацию). Или надо было вынести эти grpc-методы в отдельную структуру, как это сделано в HTTP версии сервера?

2022-11-02 06:17 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/app/event/command/create_event.go
> +type CreateEventRequestHandler interface {
Да, тут я перемудрил.

2022-11-02 06:20 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +func isOverlapped(e1, e2 event.Event) bool {
В ТЗ есть требование проверять не занята ли дата.
Разбиение по пользователям нужно бы добавить, но в ТЗ сказано что можно опустить.

2022-11-02 07:42 UTC, Nikscorp commented on hw12_13_14_15_calendar/api/grpc/EventService.proto
> +message Event {
Нет, предлагается именно так. Не вижу проблемы во вложенности.

2022-11-02 07:45 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +func isOverlapped(e1, e2 event.Event) bool {
> В ТЗ есть требование проверять не занята ли дата.

Можете пожалуйста скинуть ссылочку или лучше скрин? Перечитал и не могу этого требования найти

2022-11-02 07:56 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +func isOverlapped(e1, e2 event.Event) bool {
Ниже есть [упомянание](https://github.com/ekhvalov/golang-otus/blob/master/hw12_13_14_15_calendar/docs/12_README.md#3-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B5%D0%BC) объекты ошибок

![image](https://user-images.githubusercontent.com/6489904/199431733-612fd0ed-60d7-45c3-96c6-c9b066b7f7bd.png)

2022-11-02 18:05 UTC, Nikscorp approved these changes
Владимир, добрый вечер!

Все хорошо, основные замечания исправлены.
Добавил еще несколько комментариев в PR.
В идеале бы еще упростить логику internal/app/app.go
Впрочем, думаю это можно будет сделать в будущих заданиях.

Итоговую оценку повышаю до 10 баллов.

2022-11-03 00:17 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +func isOverlapped(e1, e2 event.Event) bool {
Спасибо

2022-11-04 01:17 UTC, merged