Hw15 calendar
ekhvalov/golang-otus pull request #19
Opened 2022-10-19 05:52 UTC by ekhvalov

2022-11-06 18:42 UTC, Nikscorp requested changes
Владимир, добрый вечер!

Проделана хорошая работа, выделил положительные места в комментариях к PR.
На данные момент есть достаточно много серьезных замечаний, в том числе:
- не тестируется SQL имплементация
- не проходят тесты
- не собираются образы
- не покрыт интеграционными тестами scheduler

Прошу поправить основные замечания, чтобы можно было зачесть работу.

>  **P.S.**
> 
> Нотация:
> 
> - CRIT: критическое замечание ведущее к значительному снижению баллов
> - WARN: некритическое замечание ведущее к незначительному снижению баллов (часто по критерию чистого кода / аккуратности)
> - NB: nota bene — что-то на что нужно обратить внимание (например в реальных проектах), совет, к снижению баллов не ведет
> - GREAT: часть проекта, которую хочется похвалить, выделить
> 
> Проверяющие тоже люди — в своих замечаниях я могу что-то упустить или ошибиться, в случае если вы не согласны с замечаниями — не стесняйтесь их оспаривать.
> 
> Если что-то нужно перепроверить, заапрувить, принять инвайт, поднять оценку, то прошу следовать данной последовательности:
> 
> 1. Написать в чате со мной с ДЗ на сайте ОТУС-а и перекинуть ДЗ на меня со статусом "Нужно проверить"
> 2. Написать на GitHub-е
> 3. Продублировать мне сообщение в корпоративном Slack-е: (Nikita Voynov)
>

2022-11-06 18:42 UTC, Nikscorp commented on hw12_13_14_15_calendar/Makefile
>  run-img: build-img
скорее всего потому, что в go.mod стоит go 1.18, а в контейнере 1.17. Не очень понимаю как локально могла проходить сборка

2022-11-06 18:42 UTC, Nikscorp commented on hw12_13_14_15_calendar/Makefile
> +	docker image rm $$(docker image ls -q -f label=otusgolang-cache=true)
WARN:
```
docker image rm $(docker image ls -q -f label=otusgolang-cache=true)
"docker image rm" requires at least 1 argument.
```

2022-11-06 18:42 UTC, Nikscorp commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +      - "8888:8080"
NB: порт для GRPC тоже нужно прокинуть, вообще grpc тестировать сильно удобней

2022-11-06 18:42 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/tests/integration/notification_test.go
> +	data, err := os.ReadFile(getEnv("TESTS_WRITER_TARGET_FILE", defaultTargetFile))
CRIT:
В итоге тест не проходит — и видимо дело не в таймаутах.

```
sender_1     | Event 1 2022-11-06 18:33:37.188124202 +0000 UTC 100600
rabbitmq_1   | 2022-11-06 18:33:57.197507+00:00 [warning] <0.556.0> closing AMQP connection <0.556.0> (172.26.0.4:42970 -> 172.26.0.2:5672, vhost: '/', user: 'guest'):
rabbitmq_1   | 2022-11-06 18:33:57.197507+00:00 [warning] <0.556.0> client unexpectedly closed TCP connection
tester_1     | --- FAIL: Test_SendNotification (40.03s)
tester_1     |     notification_test.go:62: 
tester_1     |          Error Trace:    /usr/src/calendar/internal/tests/integration/notification_test.go:62
tester_1     |          Error:          Received unexpected error:
tester_1     |                          open /tmp/writer.txt: no such file or directory
tester_1     |          Test:           Test_SendNotification
tester_1     | FAIL
tester_1     | FAIL     github.com/ekhvalov/golang-otus/hw12_13_14_15_calendar/internal/tests/integration       40.063s
tester_1     | FAIL
```

видимо не прикидывается значение для конфига куда писать ивенты
нужно поправить

2022-11-06 18:42 UTC, Nikscorp commented on hw12_13_14_15_calendar/cmd/sender/sender.go
> +	if c.TargetFile == "" {
NB: давайте всегда легировать в stdout (и при установке в файла дополнительно писать в файл) — так сильно проще отлаживать

2022-11-08 00:42 UTC, ekhvalov commented on hw12_13_14_15_calendar/Makefile
>  run-img: build-img
Исправил

2022-11-08 00:48 UTC, ekhvalov commented on hw12_13_14_15_calendar/Makefile
> +	docker image rm $$(docker image ls -q -f label=otusgolang-cache=true)
Исправил

2022-11-08 00:54 UTC, ekhvalov commented on hw12_13_14_15_calendar/Makefile
> +	cd deployments && docker-compose up -d
Исправил

2022-11-10 12:36 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/tests/integration/notification_test.go
> +func Test_SendNotification(t *testing.T) {
Исправил

2022-11-10 12:36 UTC, ekhvalov commented on hw12_13_14_15_calendar/cmd/scheduler/scheduler.go
> +	storage := memorystorage.New(memorystorage.UUIDProvider{})
Добавил SQL хранилище

2022-11-10 12:40 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/tests/integration/event_test.go
> +			sort.Strings(eventTitles)
Исправил

2022-11-10 12:42 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/tests/integration/notification_test.go
> +	data, err := os.ReadFile(getEnv("TESTS_WRITER_TARGET_FILE", defaultTargetFile))
Исправил

2022-11-10 13:00 UTC, ekhvalov commented on hw12_13_14_15_calendar/cmd/sender/sender.go
> +	if c.TargetFile == "" {
Добавил `cloneWriter`

2022-11-10 23:14 UTC, Nikscorp approved these changes
Владимир, добрый вечер!

Работа стала лучше, теперь реализация соответствует ТЗ, тесты проходят и все собирается без доработок.

Добавил несколько замечаний в PR.

Текущая оценка: 9 баллов, задание принято!
При желании можете исправить замечания и поднять баллы.

2022-11-10 23:14 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/tests/integration/event_test.go
> +package integration_test
опять же — у вас это не интеграционные тесты)

Нужно пользоваться только публичными интерфейсами: GRPC, HTTP и тут в рамках исключения чтение из файла (в нашем случае это тоже публичный интерфейс).

Весь флоу нужно тестить как будто вы внешний клиент — не нужно ходить в БД, это полумеры

2022-11-10 23:14 UTC, Nikscorp commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +version: "3.8"
из ТЗ:

У преподавателя должна быть возможность запустить весь проект с помощью команды make up (внутри docker-compose up) и погасить с помощью make down.

А тут только rmq и postgres

2022-11-11 07:36 UTC, ekhvalov commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +version: "3.8"
Исправил.

2022-11-11 07:37 UTC, ekhvalov commented on hw12_13_14_15_calendar/internal/tests/integration/event_test.go
> +package integration_test
Сделал тесты через `HTTP` и `GRPC` клиентов.

2022-11-25 11:55 UTC, merged